config/routes.rb
Rails.application.routes.draw do

  resources :exhibitions do
    collection do
      get 'categories/get_category_children', to: 'exhibitions#get_category_children', defaults: { format: 'json' }
      get 'categories/get_category_grandchildren', to: 'exhibitions#get_category_grandchildren', defaults: { format: 'json' }
    end

    member do
      post 'pay'=>   'exhibitions#pay', as: 'pay'
    end

    resources :purchases, only: [:index] do
    end

  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get "users/sign_in" => "users/sessions#new"
    get "users/sign_out" => "users/sessions#destroy"
    get 'users/purchase' => 'users/registrations#new_purchase'
    post 'users/purchase' => 'users/registrations#create_purchase'
  end

  root 'items#index'

  resources :users, only: [:index, :show, :edit, :update] do
  end

  get    'users/:id'   =>  'users#show'
  #devise_for :users, #{
  #   registrations: 'users/registrations',
  #   sessions:      'users/sessions'
  # }
  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end



  resources :cards, except: [:index, :edit, :update] do
  end

end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :brand, optional: true, dependent: :destroy
  belongs_to :category, optional: true
  belongs_to_active_hash :place
  has_many :images, dependent: :destroy, inverse_of: :exhibition

  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :brand
  include JpPrefecture
  jp_prefecture :prefecture_code
  

  validates_associated :images
  validates_associated :category

  with_options presence: true do
    validates :images
    validates :name
    validates :explanatory
    validates :cost
    validates :prefecture_code
    validates :day
    validates :price,      numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
    validates :user_id
    validates :category_id
    validates :status
  end
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController

  before_action :set_exhibition, only: [:edit, :show, :update]

  def new
    @exhibition = Exhibition.new
    @exhibition.images.build
    @category_parent_array = Category.where(ancestry: nil)
    @exhibition.build_brand
  end

  def create
    @exhibition = Exhibition.new(exhibition_params)
    if params[:img] != nil
      img = MiniMagick::Image.read(params[:img])
      img.resize_to_limit "650x387"
      img.write "public/uploads/image"
    end

    if @exhibition.save
      redirect_to exhibition_path(@exhibition), notice: '商品が出品されました'
    else
      redirect_to new_exhibition_path, notice: '商品の出品に失敗しました'
    end
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find(params[:parent_id]).children
  end

  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def show
    @exhibition = Exhibition.find(params[:id])
    @parents = Category.where(ancestry:nil)
  end

  def destroy
    @exhibition = Exhibition.find(params[:id])
    if @exhibition.user_id == current_user.id && @exhibition.destroy
      redirect_to root_path, notice: '商品が削除されました'
    else
      flash.now[:alert] = '商品の削除に失敗しました'
      render :show
    end
  end

  def confirm
    @exhibition = exhibition.new(exhibition_params)
    render :new if @post.invalid?
  end

  def edit
    @exhibition.images.build
  end

  def update
    if @exhibition.update(exhibition_params)
      redirect_to exhibition_path
    else
      render :edit
    end
  end

  def pay
    @exhibition = Exhibition.find(params[:id])

    if @exhibition.buyer_id.nil?
      card = Card.find_by(user_id: current_user.id)
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      Payjp::Charge.create(
        amount: @exhibition.price,
        customer: card.customer_id,
        currency: 'jpy'
      )
      @exhibition.update(buyer_id: current_user.id)
      redirect_to root_path
      flash[:notice] = "購入が完了しました。"
    else
      redirect_to exhibition_path(@exhibition.id), alert: "売り切れています。"
    end
  end

  def set_exhibition
    @exhibition = Exhibition.find(params[:id])
  end

  private
  def exhibition_params
    params.require(:exhibition).permit(:name, :explanatory, :cost, :prefecture_code, :day, :price, :status, :category_id, images_attributes: [:image, :id, :_destroy],brand_attributes: [:id, :name]).merge(user_id: current_user.id)
  end

  def ensure_current_user
    exhibition = Exhibition.find(params[:id])
    if exhibition.user_id != current_user.id
      redirect_to root_path
    end
  end

end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/exhibitions/_exhibition.html.haml
%li.productList
  = link_to exhibition_path(exhibition.id) do
    .productList__img
      = image_tag exhibition.images.first.image.url
    .productList__content
      .productList__content__name
        = exhibition.name
      .productList__content__details
        .productList__content__details__price
          = exhibition.price
          円
        .productList__content__details__favorite
          %i.fas.fa-star
          1
      .productList__content__taxIncluded
        (税込み)

app/views/exhibitions/edit.html.haml
= render 'devise/shared/header'

.sell
  %main.sell__head
  .sell__main
    .sell__main__content
      %h2.sell__main__content__head
        商品の情報を入力
      = form_with model: @exhibition, url: exhibition_path(@exhibition), id: 'new_exhibition', class: 'new_exhibition', local: true do |f|
        .sell__main__content__file
          .sell__main__content__file__up
            %h3.sell__main__content__file__up__head
              出品画像
              %span.form-require
                必須
              %p.sell__main__content__file__up__head__explanation
                最大5枚までアップロードできます
            .sell__main__content__file__up__box
              .up-image__group
                .previews
                  - if @exhibition.persisted?
                    - @exhibition.images.each.with_index(1) do |img, i|
                      - next if i >= 6
                      - next unless img.persisted?
                      .preview.preview_saved{{data:{name: i}},{data:{index: i}}}
                        .img_box
                          = image_tag img.image.url, data: {index: i}, class: "preview_image ", width: "120", height: "70"
                        .preview_btn
                          削除
                .images
                = f.fields_for :images, class: "images_fields" do |i| 
                  .up-image__group__dropbox{{id: "image_num_#{i.index+1}"},{data: {index: i.index+1}}}
                    = i.file_field :image, class: "exhibition_imgs__default images__hidden", id: "up_img_last", type: 'file', accept: "image/*"
                    = i.check_box :_destroy, data:{index: i.index+1}, class: 'hidden-destroy images__hidden' if i.object.persisted?

        .sell__main__content__form
          %label 
            商品
            %span.form-require
              必須
            = f.text_field :name, class: "sell__main__content__form__input", :placeholder => "商品名（必須 40文字まで)"

          %label
            商品の説明
            %span.form-require
              必須
          = f.text_area :explanatory,class: "sell__main__content__form__input", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2019年9月頃に1万円で購入したカーディガンです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"

        .sell__main__content__form
          %h3.sell__main__content__form__sub
            商品の詳細 
          .sell__main__content__form__box
            .sell__main__content__form__box__group
              %label
                カテゴリ
                %span.form-require
                  必須
              .sell__main__content__form__box__group__selects
                = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: '---'}, {id: 'parent_category'}
              %label
                ブランド
                %span.form-any
                  任意
              .sell__main__content__form__box__group__select
                = f.fields_for :brand do |brand|
                  = brand.text_field :name, placeholder: "例）シャネル", class: "sell__main__content__form__box__group__select__brand"
                  -# = f.text_field :brand_id, class: "sell__main__content__form__box__group__select__brand", placeholder: "例）シャネル"

              %label
                商品の状態
                %span.form-require
                  必須
              .sell__main__content__form__box__group__select
                = f.select :status, [["新品、未使用","新品、未使用"], ["未使用に近い","未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]],include_blank: "---", class: "sell__main__content__form__box__group__select__form"
                -# = f.select :status, {"新品、未使用":1, "未使用に近い":2,"目立った傷や汚れなし":3,"やや傷や汚れあり":4,"傷や汚れあり":5,"全体的に状態が悪い":6},{:include_blank =>"---"}, class: "sell__main__content__form__box__group__select__form"

        .sell__main__content__form
          %h3.sell__main__content__form__sub
            配送について
          .sell__main__content__form__box
            .sell__main__content__form__box__group
              %label
                配送料の負担
                %span.form-require
                  必須
              .sell__main__content__form__box__group__select
                = f.select :cost, [["送料込み(出品者負担)","送料込み(出品者負担)"], ["着払い(購入者負担)","着払い(購入者負担)"]], include_blank: "---", class: "sell__main__content__form__box__group__select__form"
                -# = f.select :cost, {"送料込み(出品者負担)":1, "着払い(購入者負担)":2},{:include_blank =>"---"}, class: "sell__main__content__form__box__group__select__form"

              %label
                発送元の地域
                %span.form-require
                  必須
              .sell__main__content__form__box__group__select
                =f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name
              %label
                発送までの日数
                %span.form-require
                  必須
              .sell__main__content__form__box__group__select
                = f.select :day, [["1~2日で発送","1~2日で発送"], ["2~3日で発送","2~3日で発送"], ["4~7日で発送","4~7日で発送"]], include_blank: "---", class: "sell__main__content__form__box__group__select__form"
                -# = f.select :day, {"1~2日で発送":1, "2~3日で発送":2, "4~7日で発送":3},{:include_blank =>"---"}, class: "sell__main__content__form__box__group__select__form"
        .sell__main__content__form
          %h3.sell__main__content__form__sub
            販売価格(300〜9,999,999)
          .sell__main__content__form__box
            %ul.sell__main__content__form__box__price
              %li.sell__main__content__form__box__price__top
                .sell__main__content__form__box__price__top__left
                  価格
                  %span.form-require
                    必須
                .sell__main__content__form__box__price__top__right
                  ¥
                  = f.text_field :price, class: "sell__main__content__form__box__price__top__right__input", placeholder: "例）300"
        .sell__main__content__button
          %div
            %p
              = link_to "", target: "_blank" do
                出品が禁止されている商品
              \/
              = link_to "", target: "_blank" do
                行為
              を必ずご確認ください。
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to "", target: "_blank" do
                偽ブランドの販売
              は犯罪であり処罰される可能性があります。
            %p
              また、出品をもちまして
              = link_to "", target: "_blank" do
                加盟店規約
              に同意したことになります。
            = f.submit "編集する", class: "sell__main__content__button__red"

  %main.sell__footer

= render 'devise/shared/footer'

app/views/exhibitions/new.html.haml
= render 'devise/shared/header'

.sell
  %main.sell__head
  .sell__main
    .sell__main__content
      %h2.sell__main__content__head
        商品の情報を入力
      = form_with model: @exhibition, url: exhibitions_path, id: 'new_exhibition', class: 'new_exhibition', local: true do |f|
        .sell__main__content__file
          .sell__main__content__file__up
            %h3.sell__main__content__file__up__head
              出品画像
              %span.form-require
                必須
              %p.sell__main__content__file__up__head__explanation
                最大5枚までアップロードできます
            .sell__main__content__file__up__box
              .up-image__group
                .previews
                  - if @exhibition.persisted?
                    - @exhibition.images.each.with_index(1) do |img, i|
                      - next if i >= 6
                      - next unless img.persisted?
                      .preview.preview_saved{{data:{name: i}},{data:{index: i}}}
                        .img_box
                          = image_tag img.image.url, data: {index: i}, class: "preview_image ", width: "120", height: "70"
                        .preview_btn
                          削除
                .images
                = f.fields_for :images, class: "images_fields" do |i| 
                  .up-image__group__dropbox{{id: "image_num_#{i.index+1}"},{data: {index: i.index+1}}}
                    = i.file_field :image, class: "exhibition_imgs__default images__hidden", id: "up_img_last", type: 'file', accept: "image/*"
                    = i.check_box :_destroy, data:{index: i.index+1}, class: 'hidden-destroy images__hidden' if i.object.persisted?

        .sell__main__content__form
          %label 
            商品
            %span.form-require
              必須
            = f.text_field :name, class: "sell__main__content__form__input", :placeholder => "商品名（必須 40文字まで)"

          %label
            商品の説明
            %span.form-require
              必須
          = f.text_area :explanatory,class: "sell__main__content__form__input", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2019年9月頃に1万円で購入したカーディガンです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"

        .sell__main__content__form
          %h3.sell__main__content__form__sub
            商品の詳細
          .sell__main__content__form__box
            .sell__main__content__form__box__group
              %label
                カテゴリ
                %span.form-require
                  必須
              .sell__main__content__form__box__group__selects
                = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: '---'}, {id: 'parent_category'}
              %label
                ブランド
                %span.form-any
                  任意
              .sell__main__content__form__box__group__select
                = f.fields_for :brand do |brand|
                  = brand.text_field :name, placeholder: "例）シャネル", class: "sell__main__content__form__box__group__select__brand"
                -# = f.text_field :brand_id, class: "sell__main__content__form__box__group__select__brand", placeholder: "例）シャネル"

              %label
                商品の状態
                %span.form-require
                  必須
              .sell__main__content__form__box__group__select
                = f.select :status, [["新品、未使用","新品、未使用"], ["未使用に近い","未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]],include_blank: "---", class: "sell__main__content__form__box__group__select__form"

        .sell__main__content__form
          %h3.sell__main__content__form__sub
            配送について
          .sell__main__content__form__box
            .sell__main__content__form__box__group
              %label
                配送料の負担
                %span.form-require
                  必須
              .sell__main__content__form__box__group__select
                = f.select :cost, [["送料込み(出品者負担)","送料込み(出品者負担)"], ["着払い(購入者負担)","着払い(購入者負担)"]], include_blank: "---", class: "sell__main__content__form__box__group__select__form"
              %label
                発送元の地域
                %span.form-require
                  必須
              .sell__main__content__form__box__group__select
                =f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name
              %label
                発送までの日数
                %span.form-require
                  必須
              .sell__main__content__form__box__group__select
                = f.select :day, [["1~2日で発送","1~2日で発送"], ["2~3日で発送","2~3日で発送"], ["4~7日で発送","4~7日で発送"]], include_blank: "---", class: "sell__main__content__form__box__group__select__form"
        .sell__main__content__form
          %h3.sell__main__content__form__sub
            販売価格(300〜9,999,999)
          .sell__main__content__form__box
            %ul.sell__main__content__form__box__price
              %li.sell__main__content__form__box__price__top
                .sell__main__content__form__box__price__top__left
                  価格
                  %span.form-require
                    必須
                .sell__main__content__form__box__price__top__right
                  ¥
                  = f.text_field :price, class: "sell__main__content__form__box__price__top__right__input", placeholder: "例）300"
        .sell__main__content__button
          %div
            %p
              = link_to "", target: "_blank" do
                出品が禁止されている商品
              \/
              = link_to "", target: "_blank" do
                行為
              を必ずご確認ください。
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to "", target: "_blank" do
                偽ブランドの販売
              は犯罪であり処罰される可能性があります。
            %p
              また、出品をもちまして
              = link_to "", target: "_blank" do
                加盟店規約
              に同意したことになります。
            = f.submit "出品する", class: "sell__main__content__button__red"

  %main.sell__footer

= render 'devise/shared/footer'

app/views/exhibitions/show.html.haml
= render 'devise/shared/header'

.exhibitions-show-wrapper
  .exhibitions-show-main
    .exhibitions-show-contents

      .exhibitions-show-box
        %h1.exhibitions-show-box__name
          = @exhibition.name

        - if user_signed_in? && current_user.id == @exhibition.user_id
          %ul.exhibitions-show-box__btn
            %li
              = link_to "編集する", edit_exhibition_path(@exhibition), class: "edit-btn", method: :get
            %li
              = link_to "削除する", "#", class: "delete-btn", method: :delete
        - else

        .exhibitions-show-box__photos
          %ul.photos-inner
            - @exhibition.images.each do |image|
              %li
                = image_tag image.image.url, class: 'show-image', :size =>'650x387'

        .exhibitions-show-box__price
          %span
            #{@exhibition.price}円
          .exhibitions-show-box__price__tax-shipfee
            %span
              （税込み）
            %span
              送料込み

        .exhibitions-show_detail
          商品内容

        .exhibitions-show_table
          %table
            %tr
              %th
                出品者
              %td
                = @exhibition.user.nickname
            %tr
              %th
                カテゴリー
              %td
                - @parents.each do |parent|
                  -if @exhibition.category_id == parent.id
                    = link_to '#' do
                      = parent.name
                      %br
                  - parent.children.each do |child|
                    -if @exhibition.category_id == child.id
                      = link_to '#' do
                        = parent.name
                        %br
                      = link_to '#' do
                        = child.name
                        %br
                    - child.children.each do |grandchild|
                      -if @exhibition.category_id == grandchild.id
                        = link_to '#' do
                          = parent.name
                        %br
                        = link_to '#' do
                          = child.name
                        %br
                        = link_to '#' do
                          = grandchild.name
                        %br
            %tr
              %th
                ブランド
              %td
                -if @exhibition.brand != nil
                  = @exhibition.brand.name
                -else
            %tr
              %th
                商品の状態
              %td
                = @exhibition.status
            %tr
              %th
                配送料の負担
              %td
                = @exhibition.cost
            %tr
              %th
                発送元の地域
              %td
                = JpPrefecture::Prefecture.find(@exhibition.prefecture_code).name
            %tr
              %th
                発送までの日数
              %td
                = @exhibition.day
            %tr
              %th
                商品の説明
              %td
                = @exhibition.explanatory

        .exhibitions-show-box_button
          - if user_signed_in? && current_user.id == @exhibition.user_id
          - elsif @exhibition.buyer_id.present?
            = link_to "#",class: "exhibitions-show-box_button__black" do
              この商品は既に購入済です
          - elsif user_signed_in?
            = link_to exhibition_purchases_path(@exhibition.id) do
              購入画面に進む
          - else
            = link_to new_user_session_path do
              購入には登録が必要です

        .exhibitions-show_several-btn
          .like
            .like-btn
              = link_to "#" do
                = icon("fas", "star")
                お気に入り 1
          .report
            .report-btn
              = link_to "#" do
                = icon("fas", "flag")
                不適切な商品を通報

= render 'devise/shared/promptDl'

= render 'devise/shared/footer'