config/routes.rb
Rails.application.routes.draw do

  resources :exhibitions do
    collection do
      get 'categories/get_category_children', to: 'exhibitions#get_category_children', defaults: { format: 'json' }
      get 'categories/get_category_grandchildren', to: 'exhibitions#get_category_grandchildren', defaults: { format: 'json' }
    end

    member do
      post 'pay'=>   'exhibitions#pay', as: 'pay'
    end

    resources :purchases, only: [:index] do
    end

  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get "users/sign_in" => "users/sessions#new"
    get "users/sign_out" => "users/sessions#destroy"
    get 'users/purchase' => 'users/registrations#new_purchase'
    post 'users/purchase' => 'users/registrations#create_purchase'
  end

  root 'items#index'

  resources :users, only: [:index, :show, :edit, :update] do
  end

  get    'users/:id'   =>  'users#show'
  #devise_for :users, #{
  #   registrations: 'users/registrations',
  #   sessions:      'users/sessions'
  # }
  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end



  resources :cards, except: [:index, :edit, :update] do
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  require "payjp"

  def index
    @exhibition = Exhibition.find(params[:exhibition_id])
    @images = @exhibition.images.all
    @purchase = Purchase.find_by(user_id: current_user.id)

    if user_signed_in?
      @user = current_user

      if @user.card.present?
        Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
        @card = Card.find_by(user_id: current_user.id)
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @customer_card = customer.cards.retrieve(@card.card_id)

        @card_brand = @customer_card.brand
        case @card_brand
        when "Visa"
          @card_src = "visa.png"
        when "JCB"
          @card_src = "JCB.png"
        when "MasterCard"
          @card_src = "mastercard.png"
        when "AmericanExpress"
          @card_src = "AmericanExpress.png"
        end

        @exp_month = @customer_card.exp_month.to_s
        @exp_year = @customer_card.exp_year.to_s.slice(2,3)

      else
      end

    else
      redirect_to user_session_path, alert: "ログインしてください。"
    end
  end

end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/index.html.haml
= render 'devise/shared/header'

.item
  .item__container
    .item__container__title 購入内容の確認
    .item__container__content.section
      .item__container__content__outline
        .item__container__content__outline__img
          = image_tag @exhibition.images.first.image.url, height: '80', width: '80', class: "item__container__content__outline__img__figure"
        .item__container__content__outline__details
          .item__container__content__outline__details__name
            %p.item__container__content__outline__details__name__text
              = @exhibition.name
            %p.item__container__content__outline__details__name__price
              %span.item__container__content__outline__details__name__price__text 送料込み (税込)
              %span.item__container__content__outline__details__name__price__pay
                - i_price = @exhibition.price.to_s
                = "¥" + i_price
    .item__container__pay.section
      .item__container__pay__box
        %span 支払い金額
        %span.item__container__pay__box__price
          = "¥" + i_price
    .item__container__PayMethod.section
      %h3.item__container__PayMethod__title 支払い方法
      .single-container
        %section.creditcard_section
          %h3 クレジットカード一覧
          - if @card.present?
            .container
              .creditcard-info
                = image_tag @card_src, alt: @card_brand
                %p.creditcard-info__number
                  = "**** **** **** " + @customer_card.last4
                %p.creditcard-info__period
                = @exp_month + " / " + @exp_year
                = button_to "削除する", card_path(@card), method: :delete, class:"creditcard-info__delete"
          - else
            = link_to new_card_path, class: "item__container__PayMethod__registration" do
              %i.fas.fa-plus-circle{"aria-hidden": true, heigh: "16", viewbox: "0 0 24 24", width: "16"}
              %span.item__container__PayMethod__registration__text 登録してください
    .item__container__shipping.section
      .item__container__shipping__box
        .item__container__shipping__box__head
          %h3.item__container__shipping__box__head__title 配送先
          = link_to "", class: "item__container__shipping__box__head__change" do
            変更する
            %i.fas.fa-chevron-right{"aria-hidden": true, heigh: "16", viewbox: "0 0 24 24", width: "16"}
        .item__container__shipping__box__address
        %p
          〒
          = @purchase.post_code
        %p
          = JpPrefecture::Prefecture.find(@purchase.prefecture_code).name
          = @purchase.city
          = @purchase.address
          = @purchase.building_name
        %p
          = current_user.family_name
          = current_user.first_name
    .item__container__purchases.section
      .item__container__purchases__box
        - if @user.card.present?
          = link_to pay_exhibition_path(@exhibition.id), method: :post do
            .item__container__purchases__box__btn
              購入する
        - else
          %p.item__container__purchases__box__text
            支払い方法を完了してください

= render 'devise/shared/footer'