config/routes.rb
Rails.application.routes.draw do

  resources :exhibitions do
    collection do
      get 'categories/get_category_children', to: 'exhibitions#get_category_children', defaults: { format: 'json' }
      get 'categories/get_category_grandchildren', to: 'exhibitions#get_category_grandchildren', defaults: { format: 'json' }
    end

    member do
      post 'pay'=>   'exhibitions#pay', as: 'pay'
    end

    resources :purchases, only: [:index] do
    end

  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get "users/sign_in" => "users/sessions#new"
    get "users/sign_out" => "users/sessions#destroy"
    get 'users/purchase' => 'users/registrations#new_purchase'
    post 'users/purchase' => 'users/registrations#create_purchase'
  end

  root 'items#index'

  resources :users, only: [:index, :show, :edit, :update] do
  end

  get    'users/:id'   =>  'users#show'
  #devise_for :users, #{
  #   registrations: 'users/registrations',
  #   sessions:      'users/sessions'
  # }
  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end



  resources :cards, except: [:index, :edit, :update] do
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @parents = Category.where(ancestry: nil)
    @exhibitions = Exhibition.order("created_at DESC").limit(5)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.haml
%header.header
  .header__inner
    .header__inner__top
      %h1.logo
        = link_to "" do
          = image_tag '/images/logo.png'
      .search
        %form.search__form{:method => "GET", }
          %input{:type => "hidden"}/
          %input.search__form__box{:placeholder => "キーワードから探す"}/
          %button{:type => "submit"}
            .submit_icon
              = image_tag '/images/icon-search 1.png'
          %input{:type => "hidden"}/

    .header__bottom
      %nav.nav

        %ul.listLeft
          %li.listLeft__item
            =  render "exhibitions/categories/category"
          %li.listLeft__item
            = link_to "ブランド", "#", class: "brBtn"
        %ul.listRight

          - if user_signed_in?
            %li.listRight__item
              = link_to 'ログアウト', destroy_user_session_path, method: :delete
            %li.listRight__item
              = link_to "マイページ", user_path(current_user.id)
          - else
            %li.listRight__item
              = link_to "ログイン", new_user_session_path, class: "login"
            %li.listRight__item
              = link_to "新規会員登録", new_user_registration_path, class: "reg"



%main

  %section.topMain
    .content
      .content__title 人生を変えるフリマアプリ
      .content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .icon
        = link_to "#", class: "appleIcon" do
          = image_tag 'https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2016-06-01&kind=iossoftware&bubble=ios_apps'
        = link_to "#", class: "googleIcon" do
          = image_tag 'https://lh3.googleusercontent.com/qF9r3ZjtgG-qyHdmjecArtKiulz1gmwL_xl9R3_fzk6igSeoN0wYbJSKEX5d_fxJRwYZJpHbqcLB3i9atl-9dOfUl9an7U43TfZ9PtQ=s0'


  %section.topIntroduction
    .title
      FURIMAが選ばれる3つの理由
    %ul.lists
      %li.list
        .list__img
          %span.list__img__num 1
          = image_tag '/images/pict-reason-01.jpg'
        .list__subtitle
          %span 3分
          ですぐに出品
        %p.list__text スマホで入力するだけで簡単に出品できる！

      %li.list
        .list__img
          %span.list__img__num 2
          = image_tag '/images/pict-reason-02.jpg'
        .list__subtitle
          %span シンプル
          で使いやすい
        %p.list__text めんどくさい入力は必要なく、検索も購入もスムーズ！

      %li.list
        .list__img
          %span.list__img__num 3
          = image_tag '/images/pict-reason-03.jpg'
        .list__subtitle
          手数量
          %span 業界最安
        %p.list__text 最大3%でお得に出品&購入！

  %section.topDescription
    .topDescription__content
      %h2.topDescription__content__title
        会員数日本一位
      %p.topDescription__content__text
        FURIMAは、フリマアプリで最も人気。<br>
        出品・購入回数も業界最多です！<br>
        ほしかったあの商品に出会えるかもしれません。
        .icon
          = link_to "#", class: "appleIcon" do
            = image_tag 'https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2016-06-01&kind=iossoftware&bubble=ios_apps'
          = link_to "#", class: "googleIcon" do
            = image_tag 'https://lh3.googleusercontent.com/qF9r3ZjtgG-qyHdmjecArtKiulz1gmwL_xl9R3_fzk6igSeoN0wYbJSKEX5d_fxJRwYZJpHbqcLB3i9atl-9dOfUl9an7U43TfZ9PtQ=s0'

  %section.topFeature
    %h2.topFeature__title FURIMAの特徴
    .cohesives
      .cohesive
        .cohesive__img
          = image_tag '/images/icon-01.png'
        %h3.cohesive__subtitle 簡単に売り買いできる
        %p.cohesive__text スマホひとつで、いつでもどこでも簡単<br>に出品・購入が可能！

      .cohesive
        .cohesive__img
          = image_tag '/images/icon-03.png'
        %h3.cohesive__subtitle 売上金は即日振込みに対応
        %p.cohesive__text 午前9時までに振込を依頼いただけれ<br>ば、翌日に指定の口座に入金いたします!

      .cohesive
        .cohesive__img
          = image_tag '/images/icon-04.png'
        %h3.cohesive__subtitle 様々な支払いに対応
        %p.cohesive__text お支払いは、クレジットカードだけでな<br>く、ポイントや売上金など多彩な方法が<br>あります。

  %section.pickup
    %h2.pickup__title ピックアップカテゴリー
    .pickup__subtitle
      = link_to "新規投稿商品", "#"
    %ul.productLists
      = render @exhibitions

  %section.pickup.pickupSecond
    %h2.pickup__title ピックアップブランド
    .pickup__subtitle
      = link_to "アーカイバ", "#"
    %ul.productLists
      %li.productList
        = link_to "#" do
          .productList__img
            = image_tag '/images/icon-04.png'
          .productList__content
            .productList__content__name asesw
            .productList__content__details
              .productList__content__details__price 1000円
              .productList__content__details__favorite
                %i.fas.fa-star
                1
            .productList__content__taxIncluded
              (税込み)

      %li.productList
        = link_to "#" do
          .productList__img
            = image_tag '/images/icon-04.png'
          .productList__content
            .productList__content__name asesw
            .productList__content__details
              .productList__content__details__price 1000円
              .productList__content__details__favorite
                %i.fas.fa-star
                1
            .productList__content__taxIncluded
              (税込み)

      %li.productList
        = link_to "#" do
          .productList__img
            = image_tag '/images/icon-04.png'
          .productList__content
            .productList__content__name asesw
            .productList__content__details
              .productList__content__details__price 1000円
              .productList__content__details__favorite
                %i.fas.fa-star
                1
            .productList__content__taxIncluded
              (税込み)

      %li.productList
        = link_to "#" do
          .productList__img
            = image_tag '/images/icon-04.png'
          .productList__content
            .productList__content__name asesw
            .productList__content__details
              .productList__content__details__price 1000円
              .productList__content__details__favorite
                %i.fas.fa-star
                1
            .productList__content__taxIncluded
              (税込み)

      %li.productList
        = link_to "#" do
          .productList__img
            = image_tag '/images/icon-04.png'
          .productList__content
            .productList__content__name asesw
            .productList__content__details
              .productList__content__details__price 1000円
              .productList__content__details__favorite
                %i.fas.fa-star
                1
            .productList__content__taxIncluded
              (税込み)

  %section.promptDl
    .promptDl__content
      .promptDl__content__title だれでもかんたん、人生を変えるフリマアプリ
      .promptDl__content__text 今すぐ無料ダウンロード！
      .icon.promptDl__content__icon
        = link_to "#", class: "appleIcon" do
          = image_tag 'https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2016-06-01&kind=iossoftware&bubble=ios_apps'
        = link_to "#", class: "googleIcon" do
          = image_tag 'https://lh3.googleusercontent.com/qF9r3ZjtgG-qyHdmjecArtKiulz1gmwL_xl9R3_fzk6igSeoN0wYbJSKEX5d_fxJRwYZJpHbqcLB3i9atl-9dOfUl9an7U43TfZ9PtQ=s0'

%footer.footer
  %ul.footer__lists

    %li.footer__lists__list
      .footer__lists__list__title FURIMAについて
      %ul.footer__lists__list__details
        %li
          = link_to "会社概要（運営会社）", "#"
        %li
          = link_to "プライバシーポリシー", "#"
        %li
          = link_to "FURIMA利用規約", "#"
        %li
          = link_to "ポイントに関する特約", "#"

    %li.footer__lists__list
      .footer__lists__list__title FURIMAを見る
      %ul.footer__lists__list__details
        %li
          = link_to "カテゴリー一覧", "#"
        %li
          = link_to "ブランド一覧", "#"

    %li.footer__lists__list
      .footer__lists__list__title ヘルプ＆ガイド
      %ul.footer__lists__list__details
        %li
          = link_to "FURIMAガイド", "#"
        %li
          = link_to "FURIMAロゴ利用ガイドライン", "#"
        %li
          = link_to "お知らせ", "#"

  .footer__logo
    = link_to "#" do
      = image_tag '/images/logo-white.png'
  %p © FURIMA

- if user_signed_in?
  = link_to new_exhibition_path, "data-turbolinks": false do
    .exhibitionBtn
      %span.exhibitionBtn__text 出品する
      = image_tag '/images/icon_camera.png', class: 'exhibitionBtn__icon'
- else
  = link_to new_user_session_path, "data-turbolinks": false do
    .exhibitionBtn
      %span.exhibitionBtn__text 出品する
      = image_tag '/images/icon_camera.png', class: 'exhibitionBtn__icon'