config/routes.rb
Rails.application.routes.draw do

  resources :exhibitions do
    collection do
      get 'categories/get_category_children', to: 'exhibitions#get_category_children', defaults: { format: 'json' }
      get 'categories/get_category_grandchildren', to: 'exhibitions#get_category_grandchildren', defaults: { format: 'json' }
    end

    member do
      post 'pay'=>   'exhibitions#pay', as: 'pay'
    end

    resources :purchases, only: [:index] do
    end

  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get "users/sign_in" => "users/sessions#new"
    get "users/sign_out" => "users/sessions#destroy"
    get 'users/purchase' => 'users/registrations#new_purchase'
    post 'users/purchase' => 'users/registrations#create_purchase'
  end

  root 'items#index'

  resources :users, only: [:index, :show, :edit, :update] do
  end

  get    'users/:id'   =>  'users#show'
  #devise_for :users, #{
  #   registrations: 'users/registrations',
  #   sessions:      'users/sessions'
  # }
  resources :categories, only: [:index] do
    member do
      get 'parent'
      get 'child'
      get 'grandchild'
    end
  end



  resources :cards, except: [:index, :edit, :update] do
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :customer_id
    validates :card_id
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :destroy, :new]

  require "payjp"

  def new
    redirect_to card_path(current_user.id) if @card.present?
  end

  def create
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]

    if params["payjp_token"].blank?
      redirect_to new_card_path
    else
      customer = Payjp::Customer.create(
        email: current_user.email,
        card: params["payjp_token"],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)

      if @card.save
        redirect_to card_path(current_user.id), notice: "クレジットカード情報を登録しました。"
      else
        redirect_to new_card_path, notice: "クレジットカード情報の登録に失敗しました。"
      end
    end

  end

  def show
    if @card.blank?
      redirect_to new_card_path
    else
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.card_id)
      @card_brand = @customer_card.brand
      case @card_brand
      when "Visa"
        @card_src = "visa.png"
      when "JCB"
        @card_src = "JCB.png"
      when "MasterCard"
        @card_src = "mastercard.png"
      when "AmericanExpress"
        @card_src = "AmericanExpress.png"
      end
      @exp_month = @customer_card.exp_month.to_s
      @exp_year = @customer_card.exp_year.to_s.slice(2,3)
    end
  end

  def destroy
    if @card.blank?
      redirect_to new_card_path
    else

      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      if @card.destroy
        redirect_to user_path(current_user.id), notice: "削除されました。"
      else
        redirect_to card_path(current_user.id), notice: "削除できませんでした。"
      end
    end
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/create.html.haml
= render 'devise/shared/header'

.create
  .create__frame
    .create__frame__message
      登録が完了しました。
    %ul.create__frame__btns

      %li.my_page_link
        = link_to "マイページに戻る", users_path(current_user.id), class: "my_page_link__btn"

      %li.credit_cards_index_link
        = link_to "登録カード一覧", card_path(current_user.id), class: "credit_cards_index_link__btn"

= render 'devise/shared/footer'

app/views/cards/new.html.haml
= render 'devise/shared/header'

.credit_cards-new
  .credit_cards-new__wrapper
    .credit_cards-new__wrapper__title
      クレジットカード情報入力
    = form_tag(cards_path, method: :post, id: 'charge-form', name: "inputForm") do
      .credit_cards-new__wrapper__form
        .credit_cards-new__wrapper__form__cardnumber
          %label
            カード番号
          %span.form-require
            必須
          %input{type: "text", class: "credit_cards-new-form-num", id: "payment_card_num", placeholder: "半角数字のみ", maxlength: "16" }
        .credit_cards-new__wrapper__form__logos
          =image_tag '/images/card_jcb_b.gif'
          =image_tag '/images/card_master_b.gif'
          =image_tag '/images/card_visa_b.gif'
        .credit_cards-new__wrapper__form__expiration-desc
          %label
            有効期限
          %span.form-require
            必須
        .credit_cards-new__wrapper__form__expiration-form
          .credit_cards-new__wrapper__form__expiration-form__date
            %select.credit_cards-new-select{id: "exp_month", type: "text"}
              %option ---
              %option{value: 1} 01
              %option{value: 2} 02
              %option{value: 3} 03
              %option{value: 4} 04
              %option{value: 5} 05
              %option{value: 6} 06
              %option{value: 7} 07
              %option{value: 8} 08
              %option{value: 9} 09
              %option{value: 10} 10
              %option{value: 11} 11
              %option{value: 12} 12
            %p 月
          .credit_cards-new__wrapper__form__expiration-form__date
            %select.credit_cards-new-select{id: "exp_year", type: "text"}
              %option ---
              %option{value: 2020} 20
              %option{value: 2021} 21
              %option{value: 2022} 22
              %option{value: 2023} 23
              %option{value: 2024} 24
              %option{value: 2025} 25
              %option{value: 2026} 26
              %option{value: 2027} 27
              %option{value: 2028} 28
              %option{value: 2029} 29
              %option{value: 2030} 30
              %option{value: 2031} 31
            %p 年
        .credit_cards-new__wrapper__form__cvc
          %label
            セキュリティコード
          %span.form-require
            必須
          %input{type: "text", class: "credit_cards-new-form-cvc", id: "payment_card_cvc", placeholder: "カード背面3桁または4桁の番号", maxlength: "4" }
        #card_token.credit_cards-new__wrapper__form__submit
          %input{type: "submit", class: "credit_cards-new__wrapper__form__submit__blue", id: "token_submit", name: "commit", value: "登録する"}

= render 'devise/shared/footer'

app/views/cards/show.html.haml
= render 'devise/shared/header'

.creditcard-main
  .creditcard-main__contents
    %h2.creditcard-main__contents__head
      登録クレジットカード情報
    %br
      = image_tag @card_src, alt: @card_brand
    %br
      = "**** **** **** " + @customer_card.last4
    %br
      = @exp_month + " / " + @exp_year
    .creditcard-button
      = link_to card_path, method: :delete do
        削除する

= render 'devise/shared/promptDl'
= render 'devise/shared/footer'